---
title: "Final Project"
output: pdf_document
---

###Import dataframe as df
```{r}
df <- healthcare.dataset.stroke.data
```

###import EDA packaves
```{r}
library(stats)
library(dplyr)
```

###removing unecessary columns
```{r}
df1 <- data.frame(df$gender, df$age, df$hypertension, df$heart_disease, df$Residence_type, df$avg_glucose_level, df$smoking_status, df$stroke, df$bmi)
```

###renaming the columns
```{r}
names(df1)[1] <- 'gender'
names(df1)[2] <- 'age'
names(df1)[3] <- 'hypertension'
names(df1)[4] <- 'heartDisease'
names(df1)[5] <- 'residenceType'
names(df1)[6] <- 'avgGlucLevel'
names(df1)[7] <- 'smokingStat'
names(df1)[8] <- 'stroke'
names(df1)[9] <- 'bmi'

```

###statistic summary of df1
```{r}
summary(df1)
```

###Counting number of occurences
```{r}
lapply(df1, table)
```

###check for missing values
```{r}
df1$bmi <- as.numeric(df1$bmi)
colSums(is.na(df1))
df1 <- na.omit(df1)

```

#heatmap
```{r}
library(ggplot2)
y <- data.matrix(df1)
```

```{r}
heatmap(y, main = 'Stroke Heatmap', cexRow = 0.5)
```
###histograms
```{r}
df1$age <- df1$age
df1$heartDisease <- as.numeric(df1$heartDisease)
df1$avgGlucLevel <- as.numeric(df1$avgGlucLevel)
```

```{r}
hist(df1$age)
hist(df1$hypertension)
hist(df1$heartDisease)
hist(df1$avgGlucLevel)
hist(df1$stroke)
hist(df1$bmi)
```

```{r}
ggplot(data = df1) + geom_bar(mapping = aes(x = residenceType))

```


